"""Add meal nutrients table

Revision ID: 16372dc1347b
Revises: fac4760f11ed
Create Date: 2024-04-17 20:18:01.050450

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "16372dc1347b"
down_revision: Union[str, None] = "fac4760f11ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meal_nutrients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("proteins", sa.Integer(), nullable=False),
        sa.Column("fats", sa.Integer(), nullable=False),
        sa.Column("carbohydrates", sa.Integer(), nullable=False),
        sa.Column("calories", sa.Integer(), nullable=False),
        sa.Column("fibers", sa.Integer(), nullable=False),
        sa.Column("sugars", sa.Integer(), nullable=False),
        sa.Column(
            "log_date",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meal_nutrients")
    # ### end Alembic commands ###
