"""Add user_goal_nutrients table

Revision ID: 0eb9d8472b0d
Revises: 16372dc1347b
Create Date: 2024-04-18 17:05:43.189690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0eb9d8472b0d"
down_revision: Union[str, None] = "16372dc1347b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_goal_nutrients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("proteins", sa.Integer(), nullable=False),
        sa.Column("fats", sa.Integer(), nullable=False),
        sa.Column("carbohydrates", sa.Integer(), nullable=False),
        sa.Column("calories", sa.Integer(), nullable=False),
        sa.Column("fibers", sa.Integer(), nullable=False),
        sa.Column("sugars", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_goal_nutrients")
    # ### end Alembic commands ###
