"""swap is_male to user_metrics

Revision ID: 1e3f5d223fdd
Revises: 8a60c47778d4
Create Date: 2024-04-10 21:57:53.711792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3f5d223fdd'
down_revision: Union[str, None] = '8a60c47778d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_male')
    op.add_column('user_metrics', sa.Column('is_male', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_metrics', 'is_male')
    op.add_column('user', sa.Column('is_male', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
