"""Add exercise and image models

Revision ID: 038e9f4f8afe
Revises: 0eb9d8472b0d
Create Date: 2024-05-10 16:19:56.952111

"""

from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import FileType

from config import settings

# revision identifiers, used by Alembic.
revision: str = "038e9f4f8afe"
down_revision: Union[str, None] = "0eb9d8472b0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", FileType(settings.files.img_storage), nullable=False),
        sa.CheckConstraint("path != ''", name="check_image_url"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exercise",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.Column("video_url", sa.String(), nullable=False),
        sa.CheckConstraint("video_url != ''", name="check_video_url"),
        sa.ForeignKeyConstraint(["image_id"], ["image.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exercise")
    op.drop_table("image")
    # ### end Alembic commands ###
